// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Qen5VDaYJemplVrDxHkyiIBEbCqx82s',
    appId: '1:269808045613:web:32d19e85111b42908032a4',
    messagingSenderId: '269808045613',
    projectId: 'habittrk',
    authDomain: 'habittrk.firebaseapp.com',
    storageBucket: 'habittrk.firebasestorage.app',
    measurementId: 'G-Q6Z204YLQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCmq5j3BrdtohWOUtR-550Z4jn4uypNt0',
    appId: '1:269808045613:android:f9e55a8426a45be28032a4',
    messagingSenderId: '269808045613',
    projectId: 'habittrk',
    storageBucket: 'habittrk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8RT4OrOPvKSDAie5VyC3mXJYTfv1dfz4',
    appId: '1:269808045613:ios:5a4ff4ed1b40cf3d8032a4',
    messagingSenderId: '269808045613',
    projectId: 'habittrk',
    storageBucket: 'habittrk.firebasestorage.app',
    iosBundleId: 'com.example.proroutine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8RT4OrOPvKSDAie5VyC3mXJYTfv1dfz4',
    appId: '1:269808045613:ios:5a4ff4ed1b40cf3d8032a4',
    messagingSenderId: '269808045613',
    projectId: 'habittrk',
    storageBucket: 'habittrk.firebasestorage.app',
    iosBundleId: 'com.example.proroutine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Qen5VDaYJemplVrDxHkyiIBEbCqx82s',
    appId: '1:269808045613:web:99c493a1a816899f8032a4',
    messagingSenderId: '269808045613',
    projectId: 'habittrk',
    authDomain: 'habittrk.firebaseapp.com',
    storageBucket: 'habittrk.firebasestorage.app',
    measurementId: 'G-LLMSNZT20N',
  );
}
